apiVersion: v1
kind: Pod
metadata:
  name: kata-dpu-test
  annotations:
    v1.multus-cni.io/default-network: openshift-ovn-kubernetes/dpf-ovn-kubernetes-kata
spec:
  runtimeClassName: kata-coldplug
  nodeSelector:
    node-role.kubernetes.io/worker-dpu: ""
  containers:
  - name: test
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "300"]
    securityContext:
      privileged: true
    resources:
      limits:
        openshift.io/kata_vfio_vfs: "1"
      requests:
        openshift.io/kata_vfio_vfs: "1"
