apiVersion: v1
kind: Pod
metadata:
  name: kata-coldplug-test
spec:
  runtimeClassName: kata-coldplug
  containers:
  - name: test
    image: registry.access.redhat.com/ubi9/ubi-minimal:latest
    command: ["sleep", "300"]
